/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestionarioeventoRouteImport } from './routes/questionarioevento'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ApiPublicHooksRunBackupRouteImport } from './routes/api.public.hooks.run-backup'

const QuestionarioeventoRoute = QuestionarioeventoRouteImport.update({
  id: '/questionarioevento',
  path: '/questionarioevento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksRunBackupRoute = ApiPublicHooksRunBackupRouteImport.update({
  id: '/api/public/hooks/run-backup',
  path: '/api/public/hooks/run-backup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/questionarioevento': typeof QuestionarioeventoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/public/hooks/run-backup': typeof ApiPublicHooksRunBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/questionarioevento': typeof QuestionarioeventoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/public/hooks/run-backup': typeof ApiPublicHooksRunBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/questionarioevento': typeof QuestionarioeventoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/public/hooks/run-backup': typeof ApiPublicHooksRunBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/questionarioevento'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/public/hooks/run-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/questionarioevento'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/public/hooks/run-backup'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/questionarioevento'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/public/hooks/run-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  QuestionarioeventoRoute: typeof QuestionarioeventoRoute
  ApiPublicHooksRunBackupRoute: typeof ApiPublicHooksRunBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/questionarioevento': {
      id: '/questionarioevento'
      path: '/questionarioevento'
      fullPath: '/questionarioevento'
      preLoaderRoute: typeof QuestionarioeventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/run-backup': {
      id: '/api/public/hooks/run-backup'
      path: '/api/public/hooks/run-backup'
      fullPath: '/api/public/hooks/run-backup'
      preLoaderRoute: typeof ApiPublicHooksRunBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  QuestionarioeventoRoute: QuestionarioeventoRoute,
  ApiPublicHooksRunBackupRoute: ApiPublicHooksRunBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
