// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Response(message, { status: 500 });
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Response('Unauthorized: No request headers available', { status: 401 });
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Response('Unauthorized: No authorization header provided', { status: 401 });
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Response('Unauthorized: No token provided', { status: 401 });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    console.log("[auth-middleware] Verifying token...");
    // getClaims is sometimes available in Lovable's environment, but let's be safe
    // and use a more standard check if it fails, or at least log it.
    let userId: string | undefined;
    let claims: any;

    try {
      const { data, error } = await (supabase.auth as any).getUser(token);
      if (error || !data?.user) {
        console.error("[auth-middleware] getUser error:", error);
        throw new Response('Unauthorized: Invalid user', { status: 401 });
      }
      userId = data.user.id;
      claims = data.user;
    } catch (err: any) {
      console.warn("[auth-middleware] getUser failed, trying getClaims:", err.message);
      if (typeof (supabase.auth as any).getClaims === 'function') {
        const { data, error } = await (supabase.auth as any).getClaims(token);
        if (error || !data?.claims) {
          throw new Response('Unauthorized: Invalid claims', { status: 401 });
        }
        userId = data.claims.sub;
        claims = data.claims;
      } else {
        throw new Response('Unauthorized: Auth method not found', { status: 401 });
      }
    }

    if (!userId) {
      throw new Response('Unauthorized: No user ID found', { status: 401 });
    }

    console.log("[auth-middleware] Auth success for user:", userId);

    return next({
      context: {
        supabase,
        userId,
        claims,
      },
    })
  }
)
